### ISSUE TITLE
Access to the data in Meshnet

### ISSUE THREAD

**Issue by kajalsanklecha** [kaylode/3d-mesh-retrieval#1]
Can you please provide public access to the drive link for dataset?

**Comment by kaylode** [comment]
Hi there,

Are you asking for the SHREC21 Dataset? If so, there is a link I embed in the README, which leads to the challenge homepage, from which you can download the dataset. 
This is the link: http://www.ivan-sipiran.com/shrec2021.html

**Comment by kajalsanklecha** [comment]
Hi,
Thank you for the quick response.
No, I'm asking about the dataset access you put up as a google drive link under the title "Dataset" -> Download original dataset.
https://drive.google.com/file/d/11GUD6EiKN-MMqGeNT8wI7ibpVfaRFC4w/view?usp=sharing
This one.

Also, could you please explain what files does the code expect in "annotations"?

**Comment by kaylode** [comment]
Oh sorry, for that dataset here is the link https://drive.google.com/drive/folders/1qrvoYOXo5Qo5EBeRU9_o9Ahs36azBxRc?usp=sharing
We split the original into multiple fold for cross-validation training, the "annotations" format is very simple if you look into the files above.

**Comment by kajalsanklecha** [comment]
Thank you so much.
