### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by Upcreat** [kaylode/3d-mesh-retrieval#2]
Hello, the author, your project is very interesting. I encountered some problems in the process of running the code. Could you please provide a more detailed documentation. Thank you!

**Comment by kaylode** [comment]
Thanks for your interest. Can you specifically describe what your problem is so I can instruct you easier?

**Comment by Upcreat** [comment]
![4715cab308290e77493e3686a1069b0](https://user-images.githubusercontent.com/83943594/209787595-57d96f23-099f-4079-be76-0dccd2005462.png)
Thank you very much for your reply! How does the red frame in the figure come from, and can you provide the corresponding code? Thank you!
